# .github/workflows/gh-pages.yml

name: Deploy Hugo site to GitHub Pages

# Give Pages and branch-push permissions
permissions:
  contents: write
  pages: write         # if you ever use the Pages API
  id-token: write      # for future-proofing

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true      # pull your theme
          fetch-depth: 0        # full history needed for pushes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
